name: cron job01

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:

env:
  WAIT_MINUTES: 360

jobs:
  job01:
    name: run task
    runs-on: ubuntu-latest
    steps:
      - name: Run the process with Docker
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/properlofi/mysterious-dawn:2.0
          options: -e DATABASE_URL=${{ secrets.DB01 }}
          run: |
            python main.py random

